apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginx
  namespace: flux-system
spec:
  healthChecks:
  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: nginx
    namespace: nginx
  interval: 1m0s
  path: ./apps/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: nginx
  timeout: 1m0s
